### ISSUE TITLE
Some questions about the PMB

### ISSUE THREAD

**Issue by fengq1a0** [LRLVEC/MarchingCubes#2]
Thank you for your implementation of PMB!

I'm learning your code and have some questions.

In your code, there are two levels of empty bocks check which is not mentioned in the paper. I'm curious that if it can improve the performance?

The code "(N - 1) / (voxelXLv1 - 1)".  It seems that some voxels are discarded, it that true?

I'm new to cuda and try to combine your implementation with a tensorRT based neural network. Thanks again!

**Comment by LRLVEC** [comment]
Yes, two levels can improve performance significantly as I mentioned that the first step (block-based-stream-reduction) reached over 10x speed up compared to original paper implementation.
Some voxels at the border are discarded so I can ignore some special conditions, in application we can simpily extend the gird border size to be integer times of the lv2 voxel size.

**Comment by fengq1a0** [comment]
Thank you for your reply! 

I notice that on Pascal/Ampere Architecture (GTX1080Ti/RTX3090)，the L2 Block size of 4 * 4 * 4 is slightly better than 4 * 4 * 8. One possible reason is that:  there are 64 SP/SM in Pascal/Ampere Architecture, but 128 SP/SM in Kepler Architecture.
